/* empty css                      */(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))f(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&f(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function f(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const m="46058905-76d6ace161caaf887286baf22",g="https://pixabay.com/api/",c=40;let a=1,l="",d=0;const u=document.querySelector(".gallery"),n=document.querySelector(".load-more"),y=document.querySelector("#loader");async function p(r,s){try{y.classList.remove("loader-hidden");const e=await axios.get(g,{params:{key:m,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:c}});return d=e.data.totalHits,e.data.hits.length===0?(iziToast.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),[]):e.data.hits}catch{return iziToast.error({title:"Error",message:"Something went wrong. Please try again later."}),[]}finally{y.classList.add("loader-hidden")}}function h(r){const s=r.map(e=>`
      <div class="photo-card">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </div>
    `).join("");u.insertAdjacentHTML("beforeend",s),P()}function b(){u.innerHTML=""}async function L(r){r.preventDefault();const s=r.target.elements.query.value.trim();if(s===""){iziToast.warning({title:"Warning",message:"Please enter a search query."});return}b(),l=s,a=1,n.style.display="none";const e=await p(l,a);e.length>0&&(h(e),a*c<d?n.style.display="block":iziToast.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}async function w(){a+=1,n.style.display="none";const r=await p(l,a);r.length>0&&(h(r),a*c>=d?(n.style.display="none",iziToast.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):n.style.display="block",v())}function v(){const{height:r}=u.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}let S=new SimpleLightbox(".gallery a");function P(){S.refresh()}document.querySelector("#search-form").addEventListener("submit",L);n.addEventListener("click",w);n.style.display="none";
//# sourceMappingURL=index.js.map
